### ISSUE TITLE
Exception when format is not JSON

### ISSUE THREAD

**Issue by bblok11** [howardhenry/grunt-onesky-export#2]
In `onFetchTranslationSuccess`, the server response is parsed as JSON, but this is not always right. In my case the server response is a PHP-array, so i get the following exception:
`Fatal error: Unexpected token <`

A fix would be to write the response data directly into the file, and skip the following lines when the response is not JSON:

``` javascript
if (body) { data = JSON.parse(body); }
if (options.sortKeys) { data = sortObject(data); }
jsonData = JSON.stringify(data, null, options.indent) + '\n';
```

**Comment by ragulka** [comment]
Having the same issue...

**Comment by howardhenry** [comment]
Thanks for pointing this out @bblok11. I had originally tailored the script to handle only JSON responses from OneSky. I've updated it so it now checks the response content-type and if it matches 'application/json' then it parses and handles the JSON data. Otherwise (eg. with content-type 'text/plain' for PHP arrays) it will now write the response data directly to the file.
